//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_s
    {
        public int id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public System.DateTime hire_date { get; set; }
        public decimal phone { get; set; }
        public int id_position { get; set; }
        public int id_departament { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual Departament_s Departament_s { get; set; }
        public virtual Position_s Position_s { get; set; }
    }
}
