//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user42_dbEntities1 : DbContext
    {
        private static user42_dbEntities1 _context;
        public user42_dbEntities1()
            : base("name=user42_dbEntities1")
        {
        }

        public static user42_dbEntities1 GetContext()
        {
            if (_context == null)
                _context = new user42_dbEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departament_s> Departament_s { get; set; }
        public virtual DbSet<Employee_s> Employee_s { get; set; }
        public virtual DbSet<Position_s> Position_s { get; set; }
    }
}
